version: '3.8'

# MERN Stack Authentication App - Docker Hub Deployment
# Run with: docker compose -f docker-compose.hub.yml up -d

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: mern_auth_mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: mern_auth
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern_network

  # Backend API
  backend:
    image: balasrinivasdevanaboyina/mern-auth-backend:latest
    container_name: mern_auth_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/mern_auth
      JWT_SECRET: ${JWT_SECRET}
      PORT: 5000
    depends_on:
      - mongodb
    networks:
      - mern_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React App
  frontend:
    image: balasrinivasdevanaboyina/mern-auth-frontend:latest
    container_name: mern_auth_frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local