version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: mern_auth_mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: mern_auth
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mern_network

  # Backend API (from Docker Hub)
  backend:
    image: balasrinivasdevanaboyina/mern-auth-backend:latest
    container_name: mern_auth_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/mern_auth
      JWT_SECRET: ${JWT_SECRET}
      PORT: 5000
    depends_on:
      - mongodb
    networks:
      - mern_network

  # Frontend React App (from Docker Hub)
  frontend:
    image: balasrinivasdevanaboyina/mern-auth-frontend:latest
    container_name: mern_auth_frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local